In [1]:
list1 = [1,2,3,4]
list2 = [5,6,7,8]

In [2]:
list1 + list2

[1, 2, 3, 4, 5, 6, 7, 8]

Output is not what is quite expected. Wanted to add up the numbers, but + sign concantenated the two lists. 

In [4]:
for i,j in zip(list1,list2):
 print (i+j)

6
8
10
12


To add this into a list, we can write this code using list append function 

In [11]:
list3 = []
for i,j in zip(list1,list2):
    list3.append(i+j)



In [12]:
list3

[6, 8, 10, 12]

We can do numerical operations in much easier way using library NumPy

In [13]:
import numpy as np 

numpy can overcome the limitations of list and can do more operations than list 

In [15]:
arr1 = np.array(list1)
arr2 = np.array(list2)


In [16]:
arr1

array([1, 2, 3, 4])

In [17]:
arr2

array([5, 6, 7, 8])

In [19]:
sum1 = arr1+arr2
sum1

array([ 6,  8, 10, 12])

in spide we can see variable explorer, in jupiter notebook use

In [20]:
%whos


Variable   Type       Data/Info
-------------------------------
arr1       ndarray    4: 4 elems, type `int64`, 32 bytes
arr2       ndarray    4: 4 elems, type `int64`, 32 bytes
arr3       ndarray    4: 4 elems, type `int64`, 32 bytes
i          int        4
j          int        8
list1      list       n=4
list2      list       n=4
list3      list       n=4
np         module     <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
sum1       ndarray    4: 4 elems, type `int64`, 32 bytes


In [21]:
#lets create a list with two lists inside 
data2 = [[1,2,3,4],[5,6,7,8]]
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [26]:
#now we will convert this into an array 
arr3 = np.array(data2)
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [28]:
#to get the dimension of the array, shows it is a 2 dimensional array
arr3.ndim

2

In [29]:
#data type of an array using dtype 
arr3.dtype

dtype('int64')

In [30]:
#shape 

arr3.shape

(2, 4)

In [37]:
#to change the datatype of an array, we need to specifically give it. 
arr4 = np.array(data2, dtype = float)
arr4

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [38]:
arr4.dtype


dtype('float64')

In [41]:
arr5 = np.array(['1','2','3','5'])
arr5   #displaying, we see datatype as u1, which means unicode or string data type

array(['1', '2', '3', '5'], dtype='<U1')

In [43]:
arr6 = np.array(arr5, dtype= int)
arr6

array([1, 2, 3, 5])

In [44]:
#now lets create list

list(range(7))

[0, 1, 2, 3, 4, 5, 6]

In [46]:
#similarly
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [47]:
np.arange(4,20)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [49]:
arr8 = np.arange(4,20,2)

In [52]:
#arrays can be reshaped to the dimesion we like as long as m*n = total number of elements in the array

arr9 = arr8.reshape(2,4)
arr9

array([[ 4,  6,  8, 10],
       [12, 14, 16, 18]])

In [54]:
arr10 = arr8.reshape(4,2)
arr10


array([[ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [55]:
#linspace converts an array into equal intervals of specified value
arr11 = np.linspace(1,30,5)
arr11

array([ 1.  ,  8.25, 15.5 , 22.75, 30.  ])

In [57]:
arr12 = np.linspace(1,12,4)
arr12

array([ 1.        ,  4.66666667,  8.33333333, 12.        ])