In [7]:
import numpy as np


In [10]:
arr = np.arange(5,20)
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
arr[5:12]  #from 5th index to 12th 

array([10, 11, 12, 13, 14, 15, 16])

In [12]:
arr[8]  #8th index

13

In [13]:
arr[5:] #from 5th index to last

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
arr[:5] # from index 0 to 4

array([5, 6, 7, 8, 9])

In [15]:
# to take more than one value from array
arr[1,2,3]
#retruns an error, we need to give it in a list 

IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed

In [16]:
arr[[1,3,5]]

array([ 6,  8, 10])

In [20]:
#next lets try making an array with -ve value. 
arr2 = np.array([[-7,5,-2,4],[5,2,7,3],[-13,10,3,-5]])
arr2

array([[ -7,   5,  -2,   4],
       [  5,   2,   7,   3],
       [-13,  10,   3,  -5]])

In [21]:
arr2[2]   #takes out the row with inxex value 2

array([-13,  10,   3,  -5])

In [22]:
arr2[0]

array([-7,  5, -2,  4])

In [23]:
# to take out multiple rows 
arr2[[0,1]]

array([[-7,  5, -2,  4],
       [ 5,  2,  7,  3]])

In [25]:
#to take out columns 
arr2[:,1]  #all rows of column with index 1

array([ 5,  2, 10])

In [26]:
arr2[:,2] #all rows of column with index 2

array([-2,  7,  3])

In [27]:
arr2[:, :2] #all rows of columns with index from 0 to 1. Note that it wont print 2 

array([[ -7,   5],
       [  5,   2],
       [-13,  10]])

In [29]:
arr2


array([[ -7,   5,  -2,   4],
       [  5,   2,   7,   3],
       [-13,  10,   3,  -5]])

In [30]:
arr2[1,1] #should return row with index 1 and column with index 1


2

In [32]:
arr3 = np.arange(10,82,2)
arr3

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80])

In [33]:
len(arr3)

36

In [37]:
#to reshape arr3 into a 6*6 array
#6*6 = 36
arr3 = arr3.reshape(6,6)
arr3

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78, 80]])

In [38]:
# lets do more operations on this. 
arr3[:,[0,2]] #this should result in all rows of columns 0 and 2

array([[10, 14],
       [22, 26],
       [34, 38],
       [46, 50],
       [58, 62],
       [70, 74]])

In [39]:
arr3[:,[0:2]]  #this results in an error

SyntaxError: invalid syntax (1952765833.py, line 1)

In [40]:
arr3[:,0:2] #this should result in all rows of columns 0 and 1

array([[10, 12],
       [22, 24],
       [34, 36],
       [46, 48],
       [58, 60],
       [70, 72]])

In [41]:
arr3


array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78, 80]])

In [42]:
arr3[:2,:] #this should take elements from rows 0,1 and all related columns

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32]])

In [43]:
arr3[:2]  #similar to above

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32]])

In [44]:
arr4 = np.array([38,40,42,50])

In [45]:
arr4


array([38, 40, 42, 50])

In [46]:
#builtin function to get the sum of all elements in an array 
arr4.sum()

170

In [47]:
#similarly with numpy we can do 
np.sum(arr4)

170

In [48]:
#to find mean
arr4.mean()

42.5

In [49]:
#using numpy
np.mean(arr4)

42.5

In [51]:
#for median
#when it comes to median, array doesnt have a median fuction 

arr4.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [52]:
np.median(arr4)

41.0

In [53]:
arr4 = arr4.reshape(2,2)

In [54]:
arr4

array([[38, 40],
       [42, 50]])

In [55]:
arr4.sum()

170

In [56]:
# to get the sum row wise or column wise, use axis key word. Axis = 1 is x axis, axis = 0 is y axis. 

arr4.sum(axis=0)

array([80, 90])

In [57]:
arr4.sum(axis = 1)

array([78, 92])

In [59]:
#can also write with out axis keyword
arr4.sum(0)

array([80, 90])

In [58]:
arr4.sum(1)

array([78, 92])

In [60]:
arr3


array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78, 80]])

In [61]:
#we can do scalar arithmetic operations 
arr3+5

array([[15, 17, 19, 21, 23, 25],
       [27, 29, 31, 33, 35, 37],
       [39, 41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59, 61],
       [63, 65, 67, 69, 71, 73],
       [75, 77, 79, 81, 83, 85]])

In [62]:
arr3-5

array([[ 5,  7,  9, 11, 13, 15],
       [17, 19, 21, 23, 25, 27],
       [29, 31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49, 51],
       [53, 55, 57, 59, 61, 63],
       [65, 67, 69, 71, 73, 75]])

In [64]:
arr3*5

array([[ 50,  60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150, 160],
       [170, 180, 190, 200, 210, 220],
       [230, 240, 250, 260, 270, 280],
       [290, 300, 310, 320, 330, 340],
       [350, 360, 370, 380, 390, 400]])

In [65]:
arr3/5

array([[ 2. ,  2.4,  2.8,  3.2,  3.6,  4. ],
       [ 4.4,  4.8,  5.2,  5.6,  6. ,  6.4],
       [ 6.8,  7.2,  7.6,  8. ,  8.4,  8.8],
       [ 9.2,  9.6, 10. , 10.4, 10.8, 11.2],
       [11.6, 12. , 12.4, 12.8, 13.2, 13.6],
       [14. , 14.4, 14.8, 15.2, 15.6, 16. ]])

In [66]:
arr3


array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78, 80]])

In [68]:
arr3[5] = -9 #will replace all the values in the row index 5 to -9
arr3

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [-9, -9, -9, -9, -9, -9]])

In [71]:
# absolute function abs(), this replaces all negative values in an array with a positve value. 
#This is when we are sure that all the values in an array are positive.
#For example, age dataset is -ve, we can use this
#applying this to arr3
arr3=np.abs(arr3)
arr3

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [ 9,  9,  9,  9,  9,  9]])

In [72]:
#sqrt function

np.sqrt(arr3)

array([[3.16227766, 3.46410162, 3.74165739, 4.        , 4.24264069,
        4.47213595],
       [4.69041576, 4.89897949, 5.09901951, 5.29150262, 5.47722558,
        5.65685425],
       [5.83095189, 6.        , 6.164414  , 6.32455532, 6.4807407 ,
        6.63324958],
       [6.78232998, 6.92820323, 7.07106781, 7.21110255, 7.34846923,
        7.48331477],
       [7.61577311, 7.74596669, 7.87400787, 8.        , 8.1240384 ,
        8.24621125],
       [3.        , 3.        , 3.        , 3.        , 3.        ,
        3.        ]])

In [73]:
type(arr3)

numpy.ndarray

In [74]:
np.zeros((5,5)) #this will print an array with all elements as zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [76]:
np.ones((5,5)) #this will print an array with all elements as one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [78]:
#identity matrix is a matrix with diagonal elements are one and rest zero. 
#eye()

np.eye(5,5)    #note: no need to declare 5,5 as tuple here 


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [79]:
A = np.arange(8).reshape(2,4)
B = np.arange(8).reshape(4,2)

In [80]:
A

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [81]:
B

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [82]:
#dot product or matrix multiplication 
#dot()

A.dot(B)


array([[28, 34],
       [76, 98]])

In [83]:
arr3

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [ 9,  9,  9,  9,  9,  9]])

In [84]:
#transpose
arr3.T

array([[10, 22, 34, 46, 58,  9],
       [12, 24, 36, 48, 60,  9],
       [14, 26, 38, 50, 62,  9],
       [16, 28, 40, 52, 64,  9],
       [18, 30, 42, 54, 66,  9],
       [20, 32, 44, 56, 68,  9]])